ClubTrophies: 0
userlist:
- 587262745
- 1293297080
- 5398258926
- 965991778
- 944737635
- 1351862795
- 1838826885
- 980860780
- 1692914062
- 885241590
- 1776839854
- 1723223576
- 1334679542
- 1627845759
- 1120841593
- 1199804150
- 1349357882
- 5162713409
- 2116328571
- 1483468372
- 658551070
- 1193654237
- 784193884
- 1790362763
user:
  587262745:
    Tag: PG28CU9QR
    Nickname: üî™MESSERNüî™
    TimeForCL: []
    Team: 1
    TimeZoneDifference: 0
    WeekTropheys: 0
    TotalTropheys: 0
  1293297080:
    Tag: V0J9V0P0
    Nickname: DaRkDeMoN
    TimeForCL: []
    Team: 7
    TimeZoneDifference: 4
    WeekTropheys: 0
    TotalTropheys: 0
  5398258926:
    Tag: 2JVROG2QJ
    Nickname: –ª–µ–æ–Ω
    TimeForCL: []
    Team: 3
    TimeZoneDifference: 2
    WeekTropheys: 0
    TotalTropheys: 0
  965991778:
    Tag: CR89LJQC
    Nickname:  ≥·µòÀ¢ƒê√∏‚Ç≤‚Ç≤…è‚ô°
    Team: 7
    TimeZoneDifference: 0
    TimeForCL: []
    WeekTropheys: 0
    TotalTropheys: 0
  944737635:
    Tag: 89RV0LUGO
    Nickname: .thaise‚ô°‚úåüèø|BS
    TimeForCL: []
    Team: 5
    TimeZoneDifference: 0
    WeekTropheys: 0
    TotalTropheys: 0
  1351862795:
    Tag: VV8UY09R
    Nickname: ‚õàÔ∏èƒê‚Ç≥‚±§‚Ç≠ ‚Ç≤‚±ß√ò‚Ç¥‚ÇÆü•Ä
    TimeForCL: []
    Team: 8
    TimeZoneDifference: 0
    WeekTropheys: 0
    TotalTropheys: 0
  1838826885:
    Tag: 89GQRL9PU
    Nickname: sanya
    TimeForCL: []
    Team: 4
    TimeZoneDifference: 0
    WeekTropheys: 0
    TotalTropheys: 0
  980860780:
    Tag: 20VVLYQ0U
    Nickname: KilMiX
    TimeForCL: []
    Team: 4
    TimeZoneDifference: 0
    WeekTropheys: 0
    TotalTropheys: 0
  1692914062:
    Tag: PQQ28YRYC
    Nickname: snyusoed
    TimeForCL: []
    Team: 1
    TimeZoneDifference: 0
    WeekTropheys: 0
    TotalTropheys: 0
  885241590:
    Tag: 9JYYULPYG
    Nickname: –í–∞–¥–∏–º –ö—É—Ä—Å–µ–¥–æ–≤
    TimeForCL: []
    Team: 7
    TimeZoneDifference: 0
    WeekTropheys: 0
    TotalTropheys: 0
  1776839854:
    Tag: 8UYGUUJVG
    Nickname: ‚ñ™Ô∏è‚ôß@[$niper]‚ôß‚ñ™Ô∏è
    TimeForCL: []
    Team: 5
    TimeZoneDifference: 0
    WeekTropheys: 0
    TotalTropheys: 0
  1723223576:
    Tag: 28PRV8UVY
    Nickname: _]LP[mr –º–∞–∫—Å06_
    TimeForCL: []
    Team: 5
    TimeZoneDifference: 0
    WeekTropheys: 0
    TotalTropheys: 0
  1334679542:
    Tag: P8GL2QCPG
    Nickname: –±–µ–≥–∞—é—â–∏–π –≥–≤–æ–∑–¥—å
    TimeForCL: []
    Team: 1
    TimeZoneDifference: 0
    WeekTropheys: 0
    TotalTropheys: 0
  1627845759:
    Tag: 8092892L2
    Nickname: _Prosto_Angel_
    TimeForCL: []
    Team: 6
    TimeZoneDifference: 0
    WeekTropheys: 0
    TotalTropheys: 0
  1120841593:
    Tag: V9VQVLC
    Nickname: SMK|SoBoring
    TimeForCL: []
    Team: 8
    TimeZoneDifference: 0
    WeekTropheys: 0
    TotalTropheys: 0
  1199804150:
    Tag: P0Q88UL90
    Nickname: ‚ô°Ô∏é·¥õ·¥è·¥ç  ú·¥Ä Ä·¥Ö è‚Ä¢
    TimeForCL: []
    Team: 6
    TimeZoneDifference: 0
    WeekTropheys: 0
    TotalTropheys: 0
  1349357882:
    Tag: Y998R89UV
    Nickname: MrGloss15
    TimeForCL: []
    Team: 4
    TimeZoneDifference: 0
    WeekTropheys: 0
    TotalTropheys: 0
  5162713409:
    Tag: VCVJPLYC
    Nickname: HAPS
    TimeForCL: []
    Team: 3
    TimeZoneDifference: 0
    WeekTropheys: 0
    TotalTropheys: 0
  2116328571:
    Tag: 8LYYRRR0
    Nickname: GCG|Trej—ÖüèØ
    Team: 6
    TimeZoneDifference: 1
    TimeForCL: []
    WeekTropheys: 0
    TotalTropheys: 0
  1483468372:
    Tag: 89JOJUQQL
    Nickname: '.: Star_E :.'
    TimeForCL: []
    Team: 2
    TimeZoneDifference: 0
    WeekTropheys: 0
    TotalTropheys: 0
  658551070:
    Tag: J9LRJU28
    Nickname: Bad Boy
    Team: 2
    TimeForCL: []
    WeekTropheys: 0
    TimeZoneDifference: 0
    TotalTropheys: 0
  784193884:
    Tag: 29R9PYUC8
    Nickname: ‚ò¢Ô∏è–°–ú–≠–†–¢–¨‚ò¢Ô∏è
    Team: 8
    TimeZoneDifference: 0
    TimeForCL: []
    WeekTropheys: 0
    TotalTropheys: 0
  1193654237:
    Tag: QQGPVJRP
    Nickname: „Ñí‰πáÁà™Ôæå‰∏®“ú
    Team: 3
    TimeZoneDifference: 0
    TimeForCL: []
    WeekTropheys: 0
    TotalTropheys: 0
  1790362763:
    Tag: YYLLRV280
    Nickname: –º–∞—Ä–∞—Ç
    Team: 2
    TimeZoneDifference: 0
    TimeForCL: []
    WeekTropheys: 0
    TotalTropheys: 0
