ClubTrophies: 0
userlist:
- 587262745
- 1293297080
- 5398258926
- 965991778
- 944737635
- 1351862795
- 1838826885
- 980860780
- 1692914062
- 885241590
- 1776839854
- 1723223576
- 1334679542
- 1627845759
- 1120841593
- 1199804150
- 1349357882
- 5162713409
- 2116328571
- 1483468372
- 658551070
- 1193654237
- 784193884
- 1790362763
user:
  587262745:
    Tag: PG28CU9QR
    Nickname: Messern
    TimeForCL:
    - '21:00'
    - '21:00'
    - '21:20'
    - '21:20'
    - '21:40'
    - '21:40'
    - '22:00'
    - '22:00'
    - '22:20'
    - '22:20'
    - '22:40'
    - '22:40'
    - '23:00'
    - '23:00'
    - '23:20'
    - '23:20'
    - '23:40'
    - '23:40'
    Team: 1
    TimeZoneDifference: 0
    WeekTropheys: 0
    TotalTropheys: 0
  1293297080:
    Tag: V0J9V0P0
    Nickname: DaRkDeMoN
    TimeForCL:
    - '17:20'
    - '17:20'
    - '17:40'
    - '17:40'
    - '18:20'
    - '18:20'
    - '18:40'
    - '18:40'
    - '19:00'
    - '19:00'
    - '19:20'
    - '19:20'
    - '20:00'
    - '20:00'
    - '20:20'
    - '20:20'
    Team: 7
    TimeZoneDifference: 4
    WeekTropheys: 0
    TotalTropheys: 0
  5398258926:
    Tag: 2JVROG2QJ
    Nickname: –ª–µ–æ–Ω
    TimeForCL:
    - '21:00'
    - '21:00'
    - '21:20'
    - '21:20'
    - '21:40'
    - '21:40'
    - '22:00'
    - '22:00'
    - '22:20'
    - '22:20'
    - '22:40'
    - '22:40'
    - '23:00'
    - '23:00'
    - '23:20'
    - '23:20'
    - '23:40'
    - '23:40'
    Team: 3
    TimeZoneDifference: 2
    WeekTropheys: 0
    TotalTropheys: 0
  965991778:
    Tag: CR89LJQC
    Nickname:  ≥·µòÀ¢ƒê√∏‚Ç≤‚Ç≤…è‚ô°Ô∏é
    Team: 7
    TimeZoneDifference: 0
    TimeForCL: []
    WeekTropheys: 0
    TotalTropheys: 0
  944737635:
    Tag: 89RV0LUGO
    Nickname: thaise
    TimeForCL: []
    Team: 5
    TimeZoneDifference: 0
    WeekTropheys: 0
    TotalTropheys: 0
  1351862795:
    Tag: VV8UY09R
    Nickname: ƒê‚Ç≥‚±§‚Ç≠ ‚Ç≤‚±ß√ò‚Ç¥‚ÇÆ
    TimeForCL:
    - '17:00'
    - '17:00'
    - '18:20'
    - '18:20'
    - '19:20'
    - '19:20'
    - '20:00'
    - '20:00'
    - '21:20'
    - '21:20'
    - '15:00'
    - '15:00'
    - '15:40'
    - '15:40'
    - '16:20'
    - '16:20'
    Team: 8
    TimeZoneDifference: 0
    WeekTropheys: 0
    TotalTropheys: 0
  1838826885:
    Tag: 89GQRL9PU
    Nickname: sanya
    TimeForCL: []
    Team: 4
    TimeZoneDifference: 0
    WeekTropheys: 0
    TotalTropheys: 0
  980860780:
    Tag: 20VVLYQ0U
    Nickname: KilMiX
    TimeForCL: []
    Team: 4
    TimeZoneDifference: 0
    WeekTropheys: 0
    TotalTropheys: 0
  1692914062:
    Tag: PQQ28YRYC
    Nickname: snysoed
    TimeForCL:
    - '18:20'
    - '18:20'
    - '18:40'
    - '18:40'
    - '19:00'
    - '19:00'
    - '19:20'
    - '19:20'
    - '19:40'
    - '19:40'
    - '20:00'
    - '20:00'
    - '20:20'
    - '20:20'
    - '20:40'
    - '20:40'
    - '21:00'
    - '21:00'
    Team: 1
    TimeZoneDifference: 0
    WeekTropheys: 0
    TotalTropheys: 0
  885241590:
    Tag: 9JYYULPYG
    Nickname: –í–∞–¥–∏–º –ö—É—Ä—Å–µ–¥–æ–≤
    TimeForCL:
    - '17:00'
    - '17:00'
    - '17:40'
    - '17:40'
    - '18:00'
    - '18:00'
    - '18:40'
    - '18:40'
    - '19:00'
    - '19:00'
    - '22:00'
    - '22:00'
    - '22:40'
    - '22:40'
    - '23:00'
    - '23:00'
    - '23:20'
    - '23:20'
    Team: 7
    TimeZoneDifference: 0
    WeekTropheys: 0
    TotalTropheys: 0
  1776839854:
    Tag: 8UYGUUJVG
    Nickname: ‚ñ™Ô∏é‚ôß@[$niper]‚ôß‚ñ™Ô∏é
    TimeForCL: []
    Team: 5
    TimeZoneDifference: 0
    WeekTropheys: 0
    TotalTropheys: 0
  1723223576:
    Tag: 28PRV8UVY
    Nickname: _]LP[mr –º–∞–∫—Å06_
    TimeForCL: []
    Team: 5
    TimeZoneDifference: 0
    WeekTropheys: 0
    TotalTropheys: 0
  1334679542:
    Tag: P8GL2QCPG
    Nickname: –±–µ–≥–∞—é—â–∏–π –≥–≤–æ–∑–¥—å
    TimeForCL:
    - '17:00'
    - '17:00'
    - '17:20'
    - '17:20'
    - '17:40'
    - '17:40'
    - '18:00'
    - '18:00'
    - '18:20'
    - '18:20'
    - '18:40'
    - '18:40'
    - '15:00'
    - '15:00'
    - '15:20'
    - '15:20'
    - '15:40'
    - '15:40'
    - '16:00'
    - '16:00'
    - '16:20'
    - '16:20'
    - '16:40'
    - '16:40'
    Team: 1
    TimeZoneDifference: 0
    WeekTropheys: 0
    TotalTropheys: 0
  1627845759:
    Tag: 8092892L2
    Nickname: _Prosto_Angel_
    TimeForCL:
    - '18:00'
    - '18:00'
    - '18:20'
    - '18:20'
    - '18:40'
    - '18:40'
    - '19:00'
    - '19:00'
    - '19:20'
    - '19:20'
    - '14:20'
    - '14:20'
    - '14:40'
    - '14:40'
    - '15:00'
    - '15:00'
    - '15:20'
    - '15:20'
    - '15:40'
    - '15:40'
    - '16:00'
    - '16:00'
    - '16:20'
    - '16:20'
    Team: 6
    TimeZoneDifference: 0
    WeekTropheys: 0
    TotalTropheys: 0
  1120841593:
    Tag: V9VQVLC
    Nickname: SMK|SoBoring
    TimeForCL: []
    Team: 8
    TimeZoneDifference: 0
    WeekTropheys: 0
    TotalTropheys: 0
  1199804150:
    Tag: P0Q88UL90
    Nickname: ‚ô°Ô∏é·¥õ·¥è·¥ç  ú·¥Ä Ä·¥Ö è‚Ä¢
    TimeForCL:
    - '17:00'
    - '17:00'
    - '18:00'
    - '18:00'
    - '19:00'
    - '19:00'
    - '19:20'
    - '19:20'
    - '19:40'
    - '19:40'
    - '20:00'
    - '20:00'
    - '21:00'
    - '21:00'
    - '16:00'
    - '16:00'
    Team: 6
    TimeZoneDifference: 0
    WeekTropheys: 0
    TotalTropheys: 0
  1349357882:
    Tag: Y998R89UV
    Nickname: MrGloss15
    TimeForCL:
    - '17:00'
    - '17:00'
    - '17:20'
    - '17:20'
    - '17:40'
    - '17:40'
    - '18:00'
    - '18:00'
    - '18:20'
    - '18:20'
    - '18:40'
    - '18:40'
    - '19:00'
    - '19:00'
    - '19:20'
    - '19:20'
    - '19:40'
    - '19:40'
    - '20:00'
    - '20:00'
    - '20:20'
    - '20:20'
    - '20:40'
    - '20:40'
    - '21:00'
    - '21:00'
    - '21:20'
    - '21:20'
    - '21:40'
    - '21:40'
    - 09:00
    - 09:00
    - 09:20
    - 09:20
    - 09:40
    - 09:40
    - '10:00'
    - '10:00'
    - '10:20'
    - '10:20'
    - '10:40'
    - '10:40'
    - '11:00'
    - '11:00'
    - '11:20'
    - '11:20'
    - '11:40'
    - '11:40'
    - '12:00'
    - '12:00'
    - '12:20'
    - '12:20'
    - '12:40'
    - '12:40'
    - '13:00'
    - '13:00'
    - '13:20'
    - '13:20'
    - '13:40'
    - '13:40'
    - '14:00'
    - '14:00'
    - '14:20'
    - '14:20'
    - '14:40'
    - '14:40'
    - '15:00'
    - '15:00'
    - '15:20'
    - '15:20'
    - '15:40'
    - '15:40'
    - '16:00'
    - '16:00'
    - '16:20'
    - '16:20'
    - '16:40'
    - '16:40'
    Team: 4
    TimeZoneDifference: 0
    WeekTropheys: 0
    TotalTropheys: 0
  5162713409:
    Tag: VCVJPLYC
    Nickname: HAPS
    TimeForCL: []
    Team: 3
    TimeZoneDifference: 0
    WeekTropheys: 0
    TotalTropheys: 0
  2116328571:
    Tag: 8LYYRRR0
    Nickname: GCG|Trej—ÖüèØ
    Team: 6
    TimeZoneDifference: 1
    TimeForCL:
    - '19:40'
    - '19:40'
    - '20:20'
    - '20:20'
    - '20:40'
    - '20:40'
    - '21:00'
    - '21:00'
    - '21:20'
    - '21:20'
    - '22:20'
    - '22:20'
    - '12:00'
    - '12:00'
    - '12:20'
    - '12:20'
    - '12:40'
    - '12:40'
    - '13:00'
    - '13:00'
    - '13:20'
    - '13:20'
    WeekTropheys: 0
    TotalTropheys: 0
  1483468372:
    Tag: 89JOJUQQL
    Nickname: '.: Star_E :.'
    TimeForCL:
    - '17:00'
    - '17:00'
    - '17:20'
    - '17:20'
    - '22:00'
    - '22:00'
    - '22:20'
    - '22:20'
    - '22:40'
    - '22:40'
    - '23:00'
    - '23:00'
    - '23:20'
    - '23:20'
    - '23:40'
    - '23:40'
    - '15:00'
    - '15:00'
    - '15:20'
    - '15:20'
    - '15:40'
    - '15:40'
    Team: 2
    TimeZoneDifference: 0
    WeekTropheys: 0
    TotalTropheys: 0
  658551070:
    Tag: J9LRJU28
    Nickname: Bad Boy
    Team: 2
    TimeForCL:
    - '17:00'
    - '17:00'
    - '17:20'
    - '17:20'
    - '17:40'
    - '17:40'
    - '18:00'
    - '18:00'
    - '18:20'
    - '18:20'
    - '18:40'
    - '18:40'
    - '19:00'
    - '19:00'
    - '19:20'
    - '19:20'
    - '19:40'
    - '19:40'
    WeekTropheys: 0
    TimeZoneDifference: 0
    TotalTropheys: 0
  784193884:
    Tag: 29R9PYUC8
    Nickname: ‚ò¢Ô∏è–°–ú–≠–†–¢–¨‚ò¢Ô∏è
    Team: 8
    TimeZoneDifference: 0
    TimeForCL: []
    WeekTropheys: 0
    TotalTropheys: 0
  1193654237:
    Tag: QQGPVJRP
    Nickname: „Ñí‰πáÁà™Ôæå‰∏®“ú
    Team: 3
    TimeZoneDifference: 0
    TimeForCL:
    - '17:00'
    - '17:00'
    - '17:20'
    - '17:20'
    - '17:40'
    - '17:40'
    - '18:00'
    - '18:00'
    - '18:20'
    - '18:20'
    - '18:40'
    - '18:40'
    - '19:00'
    - '19:00'
    - '19:20'
    - '19:20'
    - '19:40'
    - '19:40'
    - '20:00'
    - '20:00'
    - '20:20'
    - '20:20'
    - '20:40'
    - '20:40'
    - '21:00'
    - '21:00'
    - '21:20'
    - '21:20'
    - '21:40'
    - '21:40'
    - '15:00'
    - '15:00'
    - '15:20'
    - '15:20'
    - '15:40'
    - '15:40'
    - '16:00'
    - '16:00'
    - '16:20'
    - '16:20'
    - '16:40'
    - '16:40'
    WeekTropheys: 0
    TotalTropheys: 0
  1790362763:
    Tag: YYLLRV280
    Nickname: –º–∞—Ä–∞—Ç
    Team: 2
    TimeZoneDifference: 0
    TimeForCL:
    - '21:00'
    - '21:00'
    - '21:20'
    - '21:20'
    - '21:40'
    - '21:40'
    - '22:00'
    - '22:00'
    - '22:20'
    - '22:20'
    - '22:40'
    - '22:40'
    - '23:00'
    - '23:00'
    - '23:20'
    - '23:20'
    - '23:40'
    - '23:40'
    - '20:00'
    - '20:00'
    - '20:20'
    - '20:20'
    - '20:40'
    - '20:40'
    - '21:00'
    - '21:00'
    - '21:20'
    - '21:20'
    - '21:40'
    - '21:40'
    - '22:00'
    - '22:00'
    - '22:20'
    - '22:20'
    - '22:40'
    - '22:40'
    - '23:00'
    - '23:00'
    - '23:20'
    - '23:20'
    - '23:40'
    - '23:40'
    - '20:00'
    - '20:00'
    - '20:20'
    - '20:20'
    - '20:40'
    - '20:40'
    - '21:00'
    - '21:00'
    - '21:20'
    - '21:20'
    - '21:40'
    - '21:40'
    - '22:00'
    - '22:00'
    - '22:20'
    - '22:20'
    - '22:40'
    - '22:40'
    - '23:00'
    - '23:00'
    - '23:20'
    - '23:20'
    - '23:40'
    - '23:40'
    WeekTropheys: 0
    TotalTropheys: 0
